# Site settings
title: Clavelli Technologies
header-img: img/home-bg.png
email: elina.clavelli@me.com
copyright_name: eclavelli
description: > # this means to ignore newlines until "baseurl:"
  Communication and Technology
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eclavelli
learn_profile: eclavelli
email_username: elina.clavelli@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
